import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import type { StarterBrief } from "../agent/types.js";

// Basic ANSI styling
const reset = "\x1b[0m";
const bold = "\x1b[1m";
const cyan = "\x1b[36m";
const green = "\x1b[32m";
const yellow = "\x1b[33m";
const red = "\x1b[31m";
const dim = "\x1b[2m";

export function formatBriefAsTerminal(brief: StarterBrief): string {
  const lines: string[] = [];

  lines.push(`${bold}${cyan}🧭 STARTER BRIEF${reset}\n`);

  lines.push(`${bold}📌 What this issue is about:${reset}`);
  lines.push(`${brief.summary}\n`);

  lines.push(`${bold}🔍 Likely Cause:${reset}`);
  lines.push(`${brief.likelyCause}\n`);

  let diffColor = green;
  if (brief.difficulty === "medium") diffColor = yellow;
  if (brief.difficulty === "hard") diffColor = red;

  lines.push(`${bold}⚡ Difficulty:${reset} ${diffColor}${brief.difficulty.toUpperCase()}${reset} — ${brief.difficultyReason}\n`);

  lines.push(`${bold}🚀 Suggested First Step:${reset}`);
  lines.push(`${brief.suggestedFirstStep}\n`);

  if (brief.relevantFiles.length) {
    lines.push(`${bold}📁 Files Likely Worth Looking At:${reset}`);
    for (const f of brief.relevantFiles) {
      lines.push(`  • ${cyan}${f.path}${reset}`);
      lines.push(`    ${dim}${f.reason}${reset}`);
      if (f.snippet) {
        lines.push(`    ${dim}│ ${f.snippet.split("\n").join(`\n    │ `)}${reset}`);
      }
    }
    lines.push("");
  }

  if (brief.relatedHistory.length) {
    lines.push(`${bold}🔗 Related Past Work:${reset}`);
    for (const h of brief.relatedHistory) {
      lines.push(`  • ${h.title} (${cyan}${h.url}${reset})`);
      lines.push(`    ${dim}${h.summary}${reset}`);
    }
    lines.push("");
  }

  lines.push(`${dim}_Generated by issuepilot — verify before relying on it._${reset}`);

  return lines.join("\n");
}

export function formatBriefAsJson(brief: StarterBrief): string {
  return JSON.stringify(brief, null, 2);
}

export function saveBriefToFile(content: string, filePath: string): string {
  const resolved = path.resolve(process.cwd(), filePath);
  const dir = path.dirname(resolved);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(resolved, content, "utf-8");
  return resolved;
}

export function copyToClipboard(text: string): boolean {
  try {
    const platform = process.platform;
    if (platform === "win32") {
      execSync("clip", { input: text });
      return true;
    } else if (platform === "darwin") {
      execSync("pbcopy", { input: text });
      return true;
    } else {
      execSync("xclip -selection clipboard", { input: text });
      return true;
    }
  } catch {
    return false;
  }
}
