import { fetchIssue } from "./agent/fetchIssue.js";
import { runAgent, type AgentLoopOptions } from "./agent/agentLoop.js";
import type { StarterBrief } from "./agent/types.js";

export async function runPipeline(
  owner: string,
  repo: string,
  number: number,
  options: AgentLoopOptions = {}
): Promise<StarterBrief> {
  const issue = await fetchIssue(owner, repo, number);
  return runAgent(issue, options);
}

export function formatBriefAsMarkdown(brief: StarterBrief): string {
  const lines: string[] = [];
  lines.push(`### 🧭 Starter brief`);
  lines.push("");
  lines.push(`**What this issue is about:** ${brief.summary}`);
  lines.push("");
  lines.push(`**Likely cause:** ${brief.likelyCause}`);
  lines.push("");
  lines.push(`**Difficulty:** ${brief.difficulty} — ${brief.difficultyReason}`);
  lines.push("");
  lines.push(`**Suggested first step:** ${brief.suggestedFirstStep}`);
  lines.push("");

  if (brief.relevantFiles.length) {
    lines.push(`**Files likely worth looking at:**`);
    for (const f of brief.relevantFiles) {
      lines.push(`- \`${f.path}\` — ${f.reason}`);
      if (f.snippet) {
        lines.push(`  \`\`\``);
        lines.push(`  ${f.snippet.split("\n").join("\n  ")}`);
        lines.push(`  \`\`\``);
      }
    }
    lines.push("");
  }

  if (brief.relatedHistory.length) {
    lines.push(`**Related past work:**`);
    for (const h of brief.relatedHistory) {
      lines.push(`- [${h.title}](${h.url}) — ${h.summary}`);
    }
    lines.push("");
  }

  lines.push(`_Generated by issuepilot — verify before relying on it, it can be wrong._`);
  return lines.join("\n");
}
